builds:
  - main: ./cmd/vsym/main.go
    binary: vsym
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  files:
    - README.md
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    386: 32bit
    amd64: 64bit
    darwin: macOS
release:
  github:
    owner: genkiroid
    name: vsym
